Repository CSCI-GA-2820-SU23-001/shopcarts, pull requests merged in 2023-08, with the labels that each got.

#109 [R4] Align and refine UI appearances
  service/static/index.html
  service/static/items.html
  service/static/js/rest_api.js
  service/static/shopcarts.html
Labels: enhancement

#110 [R4] Add a scenario for getting a shopcart item
  features/shopcarts.feature
  service/static/js/rest_api.js
Labels: enhancement

#107 [R4] Supplement api constraints
  features/shopcarts.feature
  features/steps/web_steps.py
  service/models.py
  service/static/index.html
  service/static/items.html
  service/static/js/rest_api.js
  service/static/shopcarts.html
  tests/test_routes.py
Labels: technical debt

#113 Delete item bdd
  features/shopcarts.feature
  service/static/js/rest_api.js
Labels: enhancement

#114 Correct image tag version + fix vscode installation permission
  .devcontainer/Dockerfile
  Makefile
  deploy/deployment.yaml
Labels: technical debt

#133 Eliminate idle transactions in db after running unittests
  tests/test_models.py
Labels: technical debt

#137 Create swagger item model
  service/__init__.py
  service/config.py
  service/routes.py
Labels: enhancement

#140 Split item data model for request body and response
  service/routes.py
Labels: technical debt

#134 Set pool_recycle (maximum number of seconds a connection can persist)
  service/config.py
  service/models.py
Labels: technical debt

#139 Setup unittests for restx refactoring
  tests/__init__.py
  tests/test_routes.py
Labels: technical debt

#138 add ShopcartModel and refactor get_shopcarts API
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#141 Refactor Create Shopcarts API
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#142 Refactor Create Items API
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#135 Refactor List Items API
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#149 Refactor Delete Items API to flask-restx style
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#152 [R4] BDD scenario for Update Items API
  features/shopcarts.feature
  service/static/js/rest_api.js
  setup.cfg
Labels: enhancement

#151 List Shopcarts in Swagger
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#153 Refine + add swagger doc link to README
  .github/cicd-workflow.png
  README.md
  service/__init__.py
  service/models.py
  service/routes.py
  tests/test_routes.py
Labels: documentation

#158 Remove unused BASE_URL
  tests/__init__.py
Labels: technical debt

#161 Revert "Set pool_recycle (maximum number of seconds a connection can …
  service/config.py
  service/models.py
Labels: technical debt

#163 Refactor to use api in error_handler
  service/common/error_handlers.py
  service/models.py
  tests/test_routes.py
Labels: bug

#165 Sc112 500 fix
  service/models.py
  service/routes.py
Labels: bug, technical debt
