Repository CSCI-GA-2820-SU23-001/shopcarts, pull requests merged in 2023-07, with the labels that each got.

#32 Bug fix for db schema and model
  .gitignore
  service/models.py
  tests/factories.py
  tests/test_models.py
Labels: bug

#34 More docs and preparation for tests
  service/models.py
  service/routes.py
  tests/__init__.py
  tests/factories.py
  tests/test_cli_commands.py
  tests/test_models.py
  tests/test_routes.py
Labels: bug, documentation

#35 Implement Create Shopcart API logic
  service/routes.py
Labels: enhancement

#36 Implement Add Shopcart Item API logic
  README.md
  service/models.py
  service/routes.py
Labels: enhancement

#37 List Shopcart Items API
  README.md
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#39 Bug fix for tests: set ItemFactory.quantity to 1
  tests/factories.py
Labels: bug

#38 Get a shopcart API
  service/models.py
  service/routes.py
  tests/factories.py
  tests/test_models.py
  tests/test_routes.py
Labels: enhancement

#42 API doc template
  README.md
Labels: documentation

#45 Added more tests in test_models and test_routes
  tests/test_models.py
  tests/test_routes.py
Labels: enhancement

#46 add Get A Shopcart Item API
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#47 Update Shopcart Item API
  README.md
  service/models.py
  service/routes.py
  tests/factories.py
  tests/test_models.py
  tests/test_routes.py
Labels: documentation, enhancement

#48 add delete a shopcart item API
  service/routes.py
  tests/test_models.py
  tests/test_routes.py
Labels: enhancement

#49 Implement root url (index page) response
  service/routes.py
Labels: enhancement

#51 modify README.md for delete a shopcart item
  README.md
  service/routes.py
  tests/test_routes.py
Labels: documentation

#50 Delete a shopcart API
  README.md
  service/routes.py
  tests/test_models.py
  tests/test_routes.py
Labels: enhancement

#55 List Shopcarts API
  service/routes.py
  tests/test_models.py
  tests/test_routes.py
Labels: enhancement

#44 Resolve linter errors
  service/routes.py
  tests/test_models.py
  tests/test_routes.py
Labels: enhancement

#60 Minor fix in test cases to cover more missing test lines
  tests/test_routes.py
Labels: enhancement

#89 add Health endpoint
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#88 Create k8s cluster
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  Makefile
  README.md
Labels: enhancement

#93 Check and refine existing APIs and tests
  README.md
  service/common/error_handlers.py
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#90 added clear shopcart API and corresponding tests
  README.md
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#100 Create BDD base environment
  .devcontainer/Dockerfile
  deploy/deployment.yaml
  features/environment.py
  features/shopcarts.feature
  features/steps/shopcarts_steps.py
  features/steps/web_steps.py
  requirements.txt
  setup.cfg
Labels: enhancement
